// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v7.35.1
// source: db.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Empty } from "./google/protobuf/empty";
import { Timestamp } from "./google/protobuf/timestamp";

export const protobufPackage = "mydb";

/** -------------messages------------- */
export interface SuccessMessage {
  message: string;
}

export interface Author {
  authorId?: number | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
}

export interface Authors {
  authors: Author[];
}

export interface Book {
  bookId?: number | undefined;
  title?: string | undefined;
  isbn?: string | undefined;
  genere?: string | undefined;
  publisher?: string | undefined;
  publicationDate?: Date | undefined;
  finePerDay?: number | undefined;
  authors?: Authors | undefined;
}

export interface Books {
  books: Book[];
}

export interface BookAuthors {
  bookId?: number | undefined;
  authorId?: number | undefined;
}

export interface Address {
  houseNumber?: string | undefined;
  addressLine1?: string | undefined;
  addressLine2?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  pincode?: string | undefined;
}

export interface Member {
  memberId?: number | undefined;
  branchId?: number | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
  username?: string | undefined;
  password?: string | undefined;
  address?: Address | undefined;
  mobileNumber?: string | undefined;
  email?: string | undefined;
  joiningDate?: Date | undefined;
  isActive?: boolean | undefined;
}

export interface Members {
  members: Member[];
}

export interface CsvRequest {
  filename?: string | undefined;
  content?: Uint8Array | undefined;
}

export interface LibraryBranch {
  branchId?: number | undefined;
  branchName?: string | undefined;
  address?: string | undefined;
  phoneNumber?: string | undefined;
  email?: string | undefined;
  employeeCount?: number | undefined;
  isOperational?: Book | undefined;
}

export interface LibraryBranches {
  libraryBranches: LibraryBranch[];
}

export interface Transaction {
  transactionId?: number | undefined;
  bookId?: number | undefined;
  memberId?: number | undefined;
  issuedBranchId?: number | undefined;
  returnedBranchId?: number | undefined;
  issueDate?: Date | undefined;
  returnDate?: Date | undefined;
  isReturned?: boolean | undefined;
  fine?: number | undefined;
}

export interface Transactions {
  transactions: Transaction[];
}

export interface FetchBooksPayload {
  books: Book[];
  authors: Author[];
}

function createBaseSuccessMessage(): SuccessMessage {
  return { message: "" };
}

export const SuccessMessage: MessageFns<SuccessMessage> = {
  encode(message: SuccessMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SuccessMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSuccessMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SuccessMessage {
    return { message: isSet(object.message) ? globalThis.String(object.message) : "" };
  },

  toJSON(message: SuccessMessage): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SuccessMessage>, I>>(base?: I): SuccessMessage {
    return SuccessMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SuccessMessage>, I>>(object: I): SuccessMessage {
    const message = createBaseSuccessMessage();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseAuthor(): Author {
  return { authorId: undefined, firstName: undefined, lastName: undefined };
}

export const Author: MessageFns<Author> = {
  encode(message: Author, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authorId !== undefined) {
      writer.uint32(8).int32(message.authorId);
    }
    if (message.firstName !== undefined) {
      writer.uint32(18).string(message.firstName);
    }
    if (message.lastName !== undefined) {
      writer.uint32(26).string(message.lastName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Author {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthor();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.authorId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.firstName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.lastName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Author {
    return {
      authorId: isSet(object.authorId)
        ? globalThis.Number(object.authorId)
        : isSet(object.author_id)
        ? globalThis.Number(object.author_id)
        : undefined,
      firstName: isSet(object.firstName)
        ? globalThis.String(object.firstName)
        : isSet(object.first_name)
        ? globalThis.String(object.first_name)
        : undefined,
      lastName: isSet(object.lastName)
        ? globalThis.String(object.lastName)
        : isSet(object.last_name)
        ? globalThis.String(object.last_name)
        : undefined,
    };
  },

  toJSON(message: Author): unknown {
    const obj: any = {};
    if (message.authorId !== undefined) {
      obj.authorId = Math.round(message.authorId);
    }
    if (message.firstName !== undefined) {
      obj.firstName = message.firstName;
    }
    if (message.lastName !== undefined) {
      obj.lastName = message.lastName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Author>, I>>(base?: I): Author {
    return Author.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Author>, I>>(object: I): Author {
    const message = createBaseAuthor();
    message.authorId = object.authorId ?? undefined;
    message.firstName = object.firstName ?? undefined;
    message.lastName = object.lastName ?? undefined;
    return message;
  },
};

function createBaseAuthors(): Authors {
  return { authors: [] };
}

export const Authors: MessageFns<Authors> = {
  encode(message: Authors, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.authors) {
      Author.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Authors {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthors();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authors.push(Author.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Authors {
    return {
      authors: globalThis.Array.isArray(object?.authors) ? object.authors.map((e: any) => Author.fromJSON(e)) : [],
    };
  },

  toJSON(message: Authors): unknown {
    const obj: any = {};
    if (message.authors?.length) {
      obj.authors = message.authors.map((e) => Author.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Authors>, I>>(base?: I): Authors {
    return Authors.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Authors>, I>>(object: I): Authors {
    const message = createBaseAuthors();
    message.authors = object.authors?.map((e) => Author.fromPartial(e)) || [];
    return message;
  },
};

function createBaseBook(): Book {
  return {
    bookId: undefined,
    title: undefined,
    isbn: undefined,
    genere: undefined,
    publisher: undefined,
    publicationDate: undefined,
    finePerDay: undefined,
    authors: undefined,
  };
}

export const Book: MessageFns<Book> = {
  encode(message: Book, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bookId !== undefined) {
      writer.uint32(8).int32(message.bookId);
    }
    if (message.title !== undefined) {
      writer.uint32(18).string(message.title);
    }
    if (message.isbn !== undefined) {
      writer.uint32(26).string(message.isbn);
    }
    if (message.genere !== undefined) {
      writer.uint32(34).string(message.genere);
    }
    if (message.publisher !== undefined) {
      writer.uint32(42).string(message.publisher);
    }
    if (message.publicationDate !== undefined) {
      Timestamp.encode(toTimestamp(message.publicationDate), writer.uint32(50).fork()).join();
    }
    if (message.finePerDay !== undefined) {
      writer.uint32(56).int32(message.finePerDay);
    }
    if (message.authors !== undefined) {
      Authors.encode(message.authors, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Book {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBook();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.bookId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.isbn = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.genere = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.publisher = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.publicationDate = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.finePerDay = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.authors = Authors.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Book {
    return {
      bookId: isSet(object.bookId)
        ? globalThis.Number(object.bookId)
        : isSet(object.book_id)
        ? globalThis.Number(object.book_id)
        : undefined,
      title: isSet(object.title) ? globalThis.String(object.title) : undefined,
      isbn: isSet(object.isbn) ? globalThis.String(object.isbn) : undefined,
      genere: isSet(object.genere) ? globalThis.String(object.genere) : undefined,
      publisher: isSet(object.publisher) ? globalThis.String(object.publisher) : undefined,
      publicationDate: isSet(object.publicationDate)
        ? fromJsonTimestamp(object.publicationDate)
        : isSet(object.publication_date)
        ? fromJsonTimestamp(object.publication_date)
        : undefined,
      finePerDay: isSet(object.finePerDay)
        ? globalThis.Number(object.finePerDay)
        : isSet(object.fine_per_day)
        ? globalThis.Number(object.fine_per_day)
        : undefined,
      authors: isSet(object.authors) ? Authors.fromJSON(object.authors) : undefined,
    };
  },

  toJSON(message: Book): unknown {
    const obj: any = {};
    if (message.bookId !== undefined) {
      obj.bookId = Math.round(message.bookId);
    }
    if (message.title !== undefined) {
      obj.title = message.title;
    }
    if (message.isbn !== undefined) {
      obj.isbn = message.isbn;
    }
    if (message.genere !== undefined) {
      obj.genere = message.genere;
    }
    if (message.publisher !== undefined) {
      obj.publisher = message.publisher;
    }
    if (message.publicationDate !== undefined) {
      obj.publicationDate = message.publicationDate.toISOString();
    }
    if (message.finePerDay !== undefined) {
      obj.finePerDay = Math.round(message.finePerDay);
    }
    if (message.authors !== undefined) {
      obj.authors = Authors.toJSON(message.authors);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Book>, I>>(base?: I): Book {
    return Book.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Book>, I>>(object: I): Book {
    const message = createBaseBook();
    message.bookId = object.bookId ?? undefined;
    message.title = object.title ?? undefined;
    message.isbn = object.isbn ?? undefined;
    message.genere = object.genere ?? undefined;
    message.publisher = object.publisher ?? undefined;
    message.publicationDate = object.publicationDate ?? undefined;
    message.finePerDay = object.finePerDay ?? undefined;
    message.authors = (object.authors !== undefined && object.authors !== null)
      ? Authors.fromPartial(object.authors)
      : undefined;
    return message;
  },
};

function createBaseBooks(): Books {
  return { books: [] };
}

export const Books: MessageFns<Books> = {
  encode(message: Books, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.books) {
      Book.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Books {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBooks();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.books.push(Book.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Books {
    return { books: globalThis.Array.isArray(object?.books) ? object.books.map((e: any) => Book.fromJSON(e)) : [] };
  },

  toJSON(message: Books): unknown {
    const obj: any = {};
    if (message.books?.length) {
      obj.books = message.books.map((e) => Book.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Books>, I>>(base?: I): Books {
    return Books.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Books>, I>>(object: I): Books {
    const message = createBaseBooks();
    message.books = object.books?.map((e) => Book.fromPartial(e)) || [];
    return message;
  },
};

function createBaseBookAuthors(): BookAuthors {
  return { bookId: undefined, authorId: undefined };
}

export const BookAuthors: MessageFns<BookAuthors> = {
  encode(message: BookAuthors, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bookId !== undefined) {
      writer.uint32(8).int32(message.bookId);
    }
    if (message.authorId !== undefined) {
      writer.uint32(16).int32(message.authorId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BookAuthors {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBookAuthors();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.bookId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.authorId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BookAuthors {
    return {
      bookId: isSet(object.bookId)
        ? globalThis.Number(object.bookId)
        : isSet(object.book_id)
        ? globalThis.Number(object.book_id)
        : undefined,
      authorId: isSet(object.authorId)
        ? globalThis.Number(object.authorId)
        : isSet(object.author_id)
        ? globalThis.Number(object.author_id)
        : undefined,
    };
  },

  toJSON(message: BookAuthors): unknown {
    const obj: any = {};
    if (message.bookId !== undefined) {
      obj.bookId = Math.round(message.bookId);
    }
    if (message.authorId !== undefined) {
      obj.authorId = Math.round(message.authorId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BookAuthors>, I>>(base?: I): BookAuthors {
    return BookAuthors.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BookAuthors>, I>>(object: I): BookAuthors {
    const message = createBaseBookAuthors();
    message.bookId = object.bookId ?? undefined;
    message.authorId = object.authorId ?? undefined;
    return message;
  },
};

function createBaseAddress(): Address {
  return {
    houseNumber: undefined,
    addressLine1: undefined,
    addressLine2: undefined,
    city: undefined,
    state: undefined,
    pincode: undefined,
  };
}

export const Address: MessageFns<Address> = {
  encode(message: Address, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.houseNumber !== undefined) {
      writer.uint32(10).string(message.houseNumber);
    }
    if (message.addressLine1 !== undefined) {
      writer.uint32(18).string(message.addressLine1);
    }
    if (message.addressLine2 !== undefined) {
      writer.uint32(26).string(message.addressLine2);
    }
    if (message.city !== undefined) {
      writer.uint32(34).string(message.city);
    }
    if (message.state !== undefined) {
      writer.uint32(42).string(message.state);
    }
    if (message.pincode !== undefined) {
      writer.uint32(50).string(message.pincode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Address {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddress();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.houseNumber = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.addressLine1 = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.addressLine2 = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.city = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.state = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.pincode = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Address {
    return {
      houseNumber: isSet(object.houseNumber)
        ? globalThis.String(object.houseNumber)
        : isSet(object.house_number)
        ? globalThis.String(object.house_number)
        : undefined,
      addressLine1: isSet(object.addressLine1)
        ? globalThis.String(object.addressLine1)
        : isSet(object.address_line_1)
        ? globalThis.String(object.address_line_1)
        : undefined,
      addressLine2: isSet(object.addressLine2)
        ? globalThis.String(object.addressLine2)
        : isSet(object.address_line_2)
        ? globalThis.String(object.address_line_2)
        : undefined,
      city: isSet(object.city) ? globalThis.String(object.city) : undefined,
      state: isSet(object.state) ? globalThis.String(object.state) : undefined,
      pincode: isSet(object.pincode) ? globalThis.String(object.pincode) : undefined,
    };
  },

  toJSON(message: Address): unknown {
    const obj: any = {};
    if (message.houseNumber !== undefined) {
      obj.houseNumber = message.houseNumber;
    }
    if (message.addressLine1 !== undefined) {
      obj.addressLine1 = message.addressLine1;
    }
    if (message.addressLine2 !== undefined) {
      obj.addressLine2 = message.addressLine2;
    }
    if (message.city !== undefined) {
      obj.city = message.city;
    }
    if (message.state !== undefined) {
      obj.state = message.state;
    }
    if (message.pincode !== undefined) {
      obj.pincode = message.pincode;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Address>, I>>(base?: I): Address {
    return Address.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Address>, I>>(object: I): Address {
    const message = createBaseAddress();
    message.houseNumber = object.houseNumber ?? undefined;
    message.addressLine1 = object.addressLine1 ?? undefined;
    message.addressLine2 = object.addressLine2 ?? undefined;
    message.city = object.city ?? undefined;
    message.state = object.state ?? undefined;
    message.pincode = object.pincode ?? undefined;
    return message;
  },
};

function createBaseMember(): Member {
  return {
    memberId: undefined,
    branchId: undefined,
    firstName: undefined,
    lastName: undefined,
    username: undefined,
    password: undefined,
    address: undefined,
    mobileNumber: undefined,
    email: undefined,
    joiningDate: undefined,
    isActive: undefined,
  };
}

export const Member: MessageFns<Member> = {
  encode(message: Member, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.memberId !== undefined) {
      writer.uint32(8).int32(message.memberId);
    }
    if (message.branchId !== undefined) {
      writer.uint32(16).int32(message.branchId);
    }
    if (message.firstName !== undefined) {
      writer.uint32(26).string(message.firstName);
    }
    if (message.lastName !== undefined) {
      writer.uint32(34).string(message.lastName);
    }
    if (message.username !== undefined) {
      writer.uint32(42).string(message.username);
    }
    if (message.password !== undefined) {
      writer.uint32(50).string(message.password);
    }
    if (message.address !== undefined) {
      Address.encode(message.address, writer.uint32(58).fork()).join();
    }
    if (message.mobileNumber !== undefined) {
      writer.uint32(66).string(message.mobileNumber);
    }
    if (message.email !== undefined) {
      writer.uint32(74).string(message.email);
    }
    if (message.joiningDate !== undefined) {
      Timestamp.encode(toTimestamp(message.joiningDate), writer.uint32(82).fork()).join();
    }
    if (message.isActive !== undefined) {
      writer.uint32(88).bool(message.isActive);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Member {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMember();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.memberId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.branchId = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.firstName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.lastName = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.address = Address.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.mobileNumber = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.joiningDate = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.isActive = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Member {
    return {
      memberId: isSet(object.memberId)
        ? globalThis.Number(object.memberId)
        : isSet(object.member_id)
        ? globalThis.Number(object.member_id)
        : undefined,
      branchId: isSet(object.branchId)
        ? globalThis.Number(object.branchId)
        : isSet(object.branch_id)
        ? globalThis.Number(object.branch_id)
        : undefined,
      firstName: isSet(object.firstName)
        ? globalThis.String(object.firstName)
        : isSet(object.first_name)
        ? globalThis.String(object.first_name)
        : undefined,
      lastName: isSet(object.lastName)
        ? globalThis.String(object.lastName)
        : isSet(object.last_name)
        ? globalThis.String(object.last_name)
        : undefined,
      username: isSet(object.username) ? globalThis.String(object.username) : undefined,
      password: isSet(object.password) ? globalThis.String(object.password) : undefined,
      address: isSet(object.address) ? Address.fromJSON(object.address) : undefined,
      mobileNumber: isSet(object.mobileNumber)
        ? globalThis.String(object.mobileNumber)
        : isSet(object.mobile_number)
        ? globalThis.String(object.mobile_number)
        : undefined,
      email: isSet(object.email) ? globalThis.String(object.email) : undefined,
      joiningDate: isSet(object.joiningDate)
        ? fromJsonTimestamp(object.joiningDate)
        : isSet(object.joining_date)
        ? fromJsonTimestamp(object.joining_date)
        : undefined,
      isActive: isSet(object.isActive)
        ? globalThis.Boolean(object.isActive)
        : isSet(object.is_active)
        ? globalThis.Boolean(object.is_active)
        : undefined,
    };
  },

  toJSON(message: Member): unknown {
    const obj: any = {};
    if (message.memberId !== undefined) {
      obj.memberId = Math.round(message.memberId);
    }
    if (message.branchId !== undefined) {
      obj.branchId = Math.round(message.branchId);
    }
    if (message.firstName !== undefined) {
      obj.firstName = message.firstName;
    }
    if (message.lastName !== undefined) {
      obj.lastName = message.lastName;
    }
    if (message.username !== undefined) {
      obj.username = message.username;
    }
    if (message.password !== undefined) {
      obj.password = message.password;
    }
    if (message.address !== undefined) {
      obj.address = Address.toJSON(message.address);
    }
    if (message.mobileNumber !== undefined) {
      obj.mobileNumber = message.mobileNumber;
    }
    if (message.email !== undefined) {
      obj.email = message.email;
    }
    if (message.joiningDate !== undefined) {
      obj.joiningDate = message.joiningDate.toISOString();
    }
    if (message.isActive !== undefined) {
      obj.isActive = message.isActive;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Member>, I>>(base?: I): Member {
    return Member.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Member>, I>>(object: I): Member {
    const message = createBaseMember();
    message.memberId = object.memberId ?? undefined;
    message.branchId = object.branchId ?? undefined;
    message.firstName = object.firstName ?? undefined;
    message.lastName = object.lastName ?? undefined;
    message.username = object.username ?? undefined;
    message.password = object.password ?? undefined;
    message.address = (object.address !== undefined && object.address !== null)
      ? Address.fromPartial(object.address)
      : undefined;
    message.mobileNumber = object.mobileNumber ?? undefined;
    message.email = object.email ?? undefined;
    message.joiningDate = object.joiningDate ?? undefined;
    message.isActive = object.isActive ?? undefined;
    return message;
  },
};

function createBaseMembers(): Members {
  return { members: [] };
}

export const Members: MessageFns<Members> = {
  encode(message: Members, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.members) {
      Member.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Members {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMembers();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.members.push(Member.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Members {
    return {
      members: globalThis.Array.isArray(object?.members) ? object.members.map((e: any) => Member.fromJSON(e)) : [],
    };
  },

  toJSON(message: Members): unknown {
    const obj: any = {};
    if (message.members?.length) {
      obj.members = message.members.map((e) => Member.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Members>, I>>(base?: I): Members {
    return Members.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Members>, I>>(object: I): Members {
    const message = createBaseMembers();
    message.members = object.members?.map((e) => Member.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCsvRequest(): CsvRequest {
  return { filename: undefined, content: undefined };
}

export const CsvRequest: MessageFns<CsvRequest> = {
  encode(message: CsvRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.filename !== undefined) {
      writer.uint32(10).string(message.filename);
    }
    if (message.content !== undefined) {
      writer.uint32(18).bytes(message.content);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CsvRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCsvRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.filename = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.content = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CsvRequest {
    return {
      filename: isSet(object.filename) ? globalThis.String(object.filename) : undefined,
      content: isSet(object.content) ? bytesFromBase64(object.content) : undefined,
    };
  },

  toJSON(message: CsvRequest): unknown {
    const obj: any = {};
    if (message.filename !== undefined) {
      obj.filename = message.filename;
    }
    if (message.content !== undefined) {
      obj.content = base64FromBytes(message.content);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CsvRequest>, I>>(base?: I): CsvRequest {
    return CsvRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CsvRequest>, I>>(object: I): CsvRequest {
    const message = createBaseCsvRequest();
    message.filename = object.filename ?? undefined;
    message.content = object.content ?? undefined;
    return message;
  },
};

function createBaseLibraryBranch(): LibraryBranch {
  return {
    branchId: undefined,
    branchName: undefined,
    address: undefined,
    phoneNumber: undefined,
    email: undefined,
    employeeCount: undefined,
    isOperational: undefined,
  };
}

export const LibraryBranch: MessageFns<LibraryBranch> = {
  encode(message: LibraryBranch, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.branchId !== undefined) {
      writer.uint32(8).int32(message.branchId);
    }
    if (message.branchName !== undefined) {
      writer.uint32(18).string(message.branchName);
    }
    if (message.address !== undefined) {
      writer.uint32(26).string(message.address);
    }
    if (message.phoneNumber !== undefined) {
      writer.uint32(34).string(message.phoneNumber);
    }
    if (message.email !== undefined) {
      writer.uint32(42).string(message.email);
    }
    if (message.employeeCount !== undefined) {
      writer.uint32(48).int32(message.employeeCount);
    }
    if (message.isOperational !== undefined) {
      Book.encode(message.isOperational, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LibraryBranch {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLibraryBranch();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.branchId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.branchName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.phoneNumber = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.employeeCount = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.isOperational = Book.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LibraryBranch {
    return {
      branchId: isSet(object.branchId)
        ? globalThis.Number(object.branchId)
        : isSet(object.branch_id)
        ? globalThis.Number(object.branch_id)
        : undefined,
      branchName: isSet(object.branchName)
        ? globalThis.String(object.branchName)
        : isSet(object.branch_name)
        ? globalThis.String(object.branch_name)
        : undefined,
      address: isSet(object.address) ? globalThis.String(object.address) : undefined,
      phoneNumber: isSet(object.phoneNumber)
        ? globalThis.String(object.phoneNumber)
        : isSet(object.phone_number)
        ? globalThis.String(object.phone_number)
        : undefined,
      email: isSet(object.email) ? globalThis.String(object.email) : undefined,
      employeeCount: isSet(object.employeeCount)
        ? globalThis.Number(object.employeeCount)
        : isSet(object.employee_count)
        ? globalThis.Number(object.employee_count)
        : undefined,
      isOperational: isSet(object.isOperational)
        ? Book.fromJSON(object.isOperational)
        : isSet(object.is_operational)
        ? Book.fromJSON(object.is_operational)
        : undefined,
    };
  },

  toJSON(message: LibraryBranch): unknown {
    const obj: any = {};
    if (message.branchId !== undefined) {
      obj.branchId = Math.round(message.branchId);
    }
    if (message.branchName !== undefined) {
      obj.branchName = message.branchName;
    }
    if (message.address !== undefined) {
      obj.address = message.address;
    }
    if (message.phoneNumber !== undefined) {
      obj.phoneNumber = message.phoneNumber;
    }
    if (message.email !== undefined) {
      obj.email = message.email;
    }
    if (message.employeeCount !== undefined) {
      obj.employeeCount = Math.round(message.employeeCount);
    }
    if (message.isOperational !== undefined) {
      obj.isOperational = Book.toJSON(message.isOperational);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LibraryBranch>, I>>(base?: I): LibraryBranch {
    return LibraryBranch.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LibraryBranch>, I>>(object: I): LibraryBranch {
    const message = createBaseLibraryBranch();
    message.branchId = object.branchId ?? undefined;
    message.branchName = object.branchName ?? undefined;
    message.address = object.address ?? undefined;
    message.phoneNumber = object.phoneNumber ?? undefined;
    message.email = object.email ?? undefined;
    message.employeeCount = object.employeeCount ?? undefined;
    message.isOperational = (object.isOperational !== undefined && object.isOperational !== null)
      ? Book.fromPartial(object.isOperational)
      : undefined;
    return message;
  },
};

function createBaseLibraryBranches(): LibraryBranches {
  return { libraryBranches: [] };
}

export const LibraryBranches: MessageFns<LibraryBranches> = {
  encode(message: LibraryBranches, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.libraryBranches) {
      LibraryBranch.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LibraryBranches {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLibraryBranches();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.libraryBranches.push(LibraryBranch.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LibraryBranches {
    return {
      libraryBranches: globalThis.Array.isArray(object?.libraryBranches)
        ? object.libraryBranches.map((e: any) => LibraryBranch.fromJSON(e))
        : globalThis.Array.isArray(object?.library_branches)
        ? object.library_branches.map((e: any) => LibraryBranch.fromJSON(e))
        : [],
    };
  },

  toJSON(message: LibraryBranches): unknown {
    const obj: any = {};
    if (message.libraryBranches?.length) {
      obj.libraryBranches = message.libraryBranches.map((e) => LibraryBranch.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LibraryBranches>, I>>(base?: I): LibraryBranches {
    return LibraryBranches.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LibraryBranches>, I>>(object: I): LibraryBranches {
    const message = createBaseLibraryBranches();
    message.libraryBranches = object.libraryBranches?.map((e) => LibraryBranch.fromPartial(e)) || [];
    return message;
  },
};

function createBaseTransaction(): Transaction {
  return {
    transactionId: undefined,
    bookId: undefined,
    memberId: undefined,
    issuedBranchId: undefined,
    returnedBranchId: undefined,
    issueDate: undefined,
    returnDate: undefined,
    isReturned: undefined,
    fine: undefined,
  };
}

export const Transaction: MessageFns<Transaction> = {
  encode(message: Transaction, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.transactionId !== undefined) {
      writer.uint32(8).int32(message.transactionId);
    }
    if (message.bookId !== undefined) {
      writer.uint32(16).int32(message.bookId);
    }
    if (message.memberId !== undefined) {
      writer.uint32(24).int32(message.memberId);
    }
    if (message.issuedBranchId !== undefined) {
      writer.uint32(32).int32(message.issuedBranchId);
    }
    if (message.returnedBranchId !== undefined) {
      writer.uint32(40).int32(message.returnedBranchId);
    }
    if (message.issueDate !== undefined) {
      Timestamp.encode(toTimestamp(message.issueDate), writer.uint32(50).fork()).join();
    }
    if (message.returnDate !== undefined) {
      Timestamp.encode(toTimestamp(message.returnDate), writer.uint32(58).fork()).join();
    }
    if (message.isReturned !== undefined) {
      writer.uint32(64).bool(message.isReturned);
    }
    if (message.fine !== undefined) {
      writer.uint32(72).int32(message.fine);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Transaction {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransaction();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.transactionId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.bookId = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.memberId = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.issuedBranchId = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.returnedBranchId = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.issueDate = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.returnDate = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.isReturned = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.fine = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Transaction {
    return {
      transactionId: isSet(object.transactionId)
        ? globalThis.Number(object.transactionId)
        : isSet(object.transaction_id)
        ? globalThis.Number(object.transaction_id)
        : undefined,
      bookId: isSet(object.bookId)
        ? globalThis.Number(object.bookId)
        : isSet(object.book_id)
        ? globalThis.Number(object.book_id)
        : undefined,
      memberId: isSet(object.memberId)
        ? globalThis.Number(object.memberId)
        : isSet(object.member_id)
        ? globalThis.Number(object.member_id)
        : undefined,
      issuedBranchId: isSet(object.issuedBranchId)
        ? globalThis.Number(object.issuedBranchId)
        : isSet(object.issued_branch_id)
        ? globalThis.Number(object.issued_branch_id)
        : undefined,
      returnedBranchId: isSet(object.returnedBranchId)
        ? globalThis.Number(object.returnedBranchId)
        : isSet(object.returned_branch_id)
        ? globalThis.Number(object.returned_branch_id)
        : undefined,
      issueDate: isSet(object.issueDate)
        ? fromJsonTimestamp(object.issueDate)
        : isSet(object.issue_date)
        ? fromJsonTimestamp(object.issue_date)
        : undefined,
      returnDate: isSet(object.returnDate)
        ? fromJsonTimestamp(object.returnDate)
        : isSet(object.return_date)
        ? fromJsonTimestamp(object.return_date)
        : undefined,
      isReturned: isSet(object.isReturned)
        ? globalThis.Boolean(object.isReturned)
        : isSet(object.is_returned)
        ? globalThis.Boolean(object.is_returned)
        : undefined,
      fine: isSet(object.fine) ? globalThis.Number(object.fine) : undefined,
    };
  },

  toJSON(message: Transaction): unknown {
    const obj: any = {};
    if (message.transactionId !== undefined) {
      obj.transactionId = Math.round(message.transactionId);
    }
    if (message.bookId !== undefined) {
      obj.bookId = Math.round(message.bookId);
    }
    if (message.memberId !== undefined) {
      obj.memberId = Math.round(message.memberId);
    }
    if (message.issuedBranchId !== undefined) {
      obj.issuedBranchId = Math.round(message.issuedBranchId);
    }
    if (message.returnedBranchId !== undefined) {
      obj.returnedBranchId = Math.round(message.returnedBranchId);
    }
    if (message.issueDate !== undefined) {
      obj.issueDate = message.issueDate.toISOString();
    }
    if (message.returnDate !== undefined) {
      obj.returnDate = message.returnDate.toISOString();
    }
    if (message.isReturned !== undefined) {
      obj.isReturned = message.isReturned;
    }
    if (message.fine !== undefined) {
      obj.fine = Math.round(message.fine);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Transaction>, I>>(base?: I): Transaction {
    return Transaction.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Transaction>, I>>(object: I): Transaction {
    const message = createBaseTransaction();
    message.transactionId = object.transactionId ?? undefined;
    message.bookId = object.bookId ?? undefined;
    message.memberId = object.memberId ?? undefined;
    message.issuedBranchId = object.issuedBranchId ?? undefined;
    message.returnedBranchId = object.returnedBranchId ?? undefined;
    message.issueDate = object.issueDate ?? undefined;
    message.returnDate = object.returnDate ?? undefined;
    message.isReturned = object.isReturned ?? undefined;
    message.fine = object.fine ?? undefined;
    return message;
  },
};

function createBaseTransactions(): Transactions {
  return { transactions: [] };
}

export const Transactions: MessageFns<Transactions> = {
  encode(message: Transactions, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.transactions) {
      Transaction.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Transactions {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransactions();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.transactions.push(Transaction.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Transactions {
    return {
      transactions: globalThis.Array.isArray(object?.transactions)
        ? object.transactions.map((e: any) => Transaction.fromJSON(e))
        : [],
    };
  },

  toJSON(message: Transactions): unknown {
    const obj: any = {};
    if (message.transactions?.length) {
      obj.transactions = message.transactions.map((e) => Transaction.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Transactions>, I>>(base?: I): Transactions {
    return Transactions.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Transactions>, I>>(object: I): Transactions {
    const message = createBaseTransactions();
    message.transactions = object.transactions?.map((e) => Transaction.fromPartial(e)) || [];
    return message;
  },
};

function createBaseFetchBooksPayload(): FetchBooksPayload {
  return { books: [], authors: [] };
}

export const FetchBooksPayload: MessageFns<FetchBooksPayload> = {
  encode(message: FetchBooksPayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.books) {
      Book.encode(v!, writer.uint32(10).fork()).join();
    }
    for (const v of message.authors) {
      Author.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FetchBooksPayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFetchBooksPayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.books.push(Book.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.authors.push(Author.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FetchBooksPayload {
    return {
      books: globalThis.Array.isArray(object?.books) ? object.books.map((e: any) => Book.fromJSON(e)) : [],
      authors: globalThis.Array.isArray(object?.authors) ? object.authors.map((e: any) => Author.fromJSON(e)) : [],
    };
  },

  toJSON(message: FetchBooksPayload): unknown {
    const obj: any = {};
    if (message.books?.length) {
      obj.books = message.books.map((e) => Book.toJSON(e));
    }
    if (message.authors?.length) {
      obj.authors = message.authors.map((e) => Author.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FetchBooksPayload>, I>>(base?: I): FetchBooksPayload {
    return FetchBooksPayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FetchBooksPayload>, I>>(object: I): FetchBooksPayload {
    const message = createBaseFetchBooksPayload();
    message.books = object.books?.map((e) => Book.fromPartial(e)) || [];
    message.authors = object.authors?.map((e) => Author.fromPartial(e)) || [];
    return message;
  },
};

/** -------------service declaration------------- */
export interface LibraryManagement {
  create_tables(request: Empty): Promise<SuccessMessage>;
  /** insert methods */
  insert_books(request: Books): Promise<SuccessMessage>;
  insert_books_bulk(request: CsvRequest): Promise<SuccessMessage>;
  insert_authors(request: Authors): Promise<SuccessMessage>;
  insert_members(request: Members): Promise<SuccessMessage>;
  insert_branch_details(request: LibraryBranch): Promise<SuccessMessage>;
  insert_transaction(request: Transaction): Promise<SuccessMessage>;
  /** fetch methods */
  fetch_authors(request: Author): Promise<Authors>;
  fetch_members(request: Member): Promise<Members>;
  fetch_books(request: FetchBooksPayload): Promise<FetchBooksPayload>;
  fetch_transactions(request: Transaction): Promise<Transactions>;
  /** update methods */
  update_member(request: Member): Promise<SuccessMessage>;
  update_book(request: Book): Promise<SuccessMessage>;
  update_transaction(request: Transaction): Promise<SuccessMessage>;
  /** delete methods */
  delete_member(request: Member): Promise<SuccessMessage>;
  delete_book(request: Book): Promise<SuccessMessage>;
  delete_library_branch(request: LibraryBranch): Promise<SuccessMessage>;
}

export const LibraryManagementServiceName = "mydb.LibraryManagement";
export class LibraryManagementClientImpl implements LibraryManagement {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || LibraryManagementServiceName;
    this.rpc = rpc;
    this.create_tables = this.create_tables.bind(this);
    this.insert_books = this.insert_books.bind(this);
    this.insert_books_bulk = this.insert_books_bulk.bind(this);
    this.insert_authors = this.insert_authors.bind(this);
    this.insert_members = this.insert_members.bind(this);
    this.insert_branch_details = this.insert_branch_details.bind(this);
    this.insert_transaction = this.insert_transaction.bind(this);
    this.fetch_authors = this.fetch_authors.bind(this);
    this.fetch_members = this.fetch_members.bind(this);
    this.fetch_books = this.fetch_books.bind(this);
    this.fetch_transactions = this.fetch_transactions.bind(this);
    this.update_member = this.update_member.bind(this);
    this.update_book = this.update_book.bind(this);
    this.update_transaction = this.update_transaction.bind(this);
    this.delete_member = this.delete_member.bind(this);
    this.delete_book = this.delete_book.bind(this);
    this.delete_library_branch = this.delete_library_branch.bind(this);
  }
  create_tables(request: Empty): Promise<SuccessMessage> {
    const data = Empty.encode(request).finish();
    const promise = this.rpc.request(this.service, "create_tables", data);
    return promise.then((data) => SuccessMessage.decode(new BinaryReader(data)));
  }

  insert_books(request: Books): Promise<SuccessMessage> {
    const data = Books.encode(request).finish();
    const promise = this.rpc.request(this.service, "insert_books", data);
    return promise.then((data) => SuccessMessage.decode(new BinaryReader(data)));
  }

  insert_books_bulk(request: CsvRequest): Promise<SuccessMessage> {
    const data = CsvRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "insert_books_bulk", data);
    return promise.then((data) => SuccessMessage.decode(new BinaryReader(data)));
  }

  insert_authors(request: Authors): Promise<SuccessMessage> {
    const data = Authors.encode(request).finish();
    const promise = this.rpc.request(this.service, "insert_authors", data);
    return promise.then((data) => SuccessMessage.decode(new BinaryReader(data)));
  }

  insert_members(request: Members): Promise<SuccessMessage> {
    const data = Members.encode(request).finish();
    const promise = this.rpc.request(this.service, "insert_members", data);
    return promise.then((data) => SuccessMessage.decode(new BinaryReader(data)));
  }

  insert_branch_details(request: LibraryBranch): Promise<SuccessMessage> {
    const data = LibraryBranch.encode(request).finish();
    const promise = this.rpc.request(this.service, "insert_branch_details", data);
    return promise.then((data) => SuccessMessage.decode(new BinaryReader(data)));
  }

  insert_transaction(request: Transaction): Promise<SuccessMessage> {
    const data = Transaction.encode(request).finish();
    const promise = this.rpc.request(this.service, "insert_transaction", data);
    return promise.then((data) => SuccessMessage.decode(new BinaryReader(data)));
  }

  fetch_authors(request: Author): Promise<Authors> {
    const data = Author.encode(request).finish();
    const promise = this.rpc.request(this.service, "fetch_authors", data);
    return promise.then((data) => Authors.decode(new BinaryReader(data)));
  }

  fetch_members(request: Member): Promise<Members> {
    const data = Member.encode(request).finish();
    const promise = this.rpc.request(this.service, "fetch_members", data);
    return promise.then((data) => Members.decode(new BinaryReader(data)));
  }

  fetch_books(request: FetchBooksPayload): Promise<FetchBooksPayload> {
    const data = FetchBooksPayload.encode(request).finish();
    const promise = this.rpc.request(this.service, "fetch_books", data);
    return promise.then((data) => FetchBooksPayload.decode(new BinaryReader(data)));
  }

  fetch_transactions(request: Transaction): Promise<Transactions> {
    const data = Transaction.encode(request).finish();
    const promise = this.rpc.request(this.service, "fetch_transactions", data);
    return promise.then((data) => Transactions.decode(new BinaryReader(data)));
  }

  update_member(request: Member): Promise<SuccessMessage> {
    const data = Member.encode(request).finish();
    const promise = this.rpc.request(this.service, "update_member", data);
    return promise.then((data) => SuccessMessage.decode(new BinaryReader(data)));
  }

  update_book(request: Book): Promise<SuccessMessage> {
    const data = Book.encode(request).finish();
    const promise = this.rpc.request(this.service, "update_book", data);
    return promise.then((data) => SuccessMessage.decode(new BinaryReader(data)));
  }

  update_transaction(request: Transaction): Promise<SuccessMessage> {
    const data = Transaction.encode(request).finish();
    const promise = this.rpc.request(this.service, "update_transaction", data);
    return promise.then((data) => SuccessMessage.decode(new BinaryReader(data)));
  }

  delete_member(request: Member): Promise<SuccessMessage> {
    const data = Member.encode(request).finish();
    const promise = this.rpc.request(this.service, "delete_member", data);
    return promise.then((data) => SuccessMessage.decode(new BinaryReader(data)));
  }

  delete_book(request: Book): Promise<SuccessMessage> {
    const data = Book.encode(request).finish();
    const promise = this.rpc.request(this.service, "delete_book", data);
    return promise.then((data) => SuccessMessage.decode(new BinaryReader(data)));
  }

  delete_library_branch(request: LibraryBranch): Promise<SuccessMessage> {
    const data = LibraryBranch.encode(request).finish();
    const promise = this.rpc.request(this.service, "delete_library_branch", data);
    return promise.then((data) => SuccessMessage.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
