# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import db_pb2 as db__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in db_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LibraryManagementStub:
    """-------------service declaration-------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create_tables = channel.unary_unary(
                '/mydb.LibraryManagement/create_tables',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=db__pb2.SuccessMessage.FromString,
                _registered_method=True)
        self.insert_book = channel.unary_unary(
                '/mydb.LibraryManagement/insert_book',
                request_serializer=db__pb2.Book.SerializeToString,
                response_deserializer=db__pb2.SuccessMessage.FromString,
                _registered_method=True)
        self.insert_books_bulk = channel.unary_unary(
                '/mydb.LibraryManagement/insert_books_bulk',
                request_serializer=db__pb2.CsvRequest.SerializeToString,
                response_deserializer=db__pb2.SuccessMessage.FromString,
                _registered_method=True)
        self.insert_authors = channel.unary_unary(
                '/mydb.LibraryManagement/insert_authors',
                request_serializer=db__pb2.Authors.SerializeToString,
                response_deserializer=db__pb2.SuccessMessage.FromString,
                _registered_method=True)
        self.insert_members = channel.unary_unary(
                '/mydb.LibraryManagement/insert_members',
                request_serializer=db__pb2.Members.SerializeToString,
                response_deserializer=db__pb2.SuccessMessage.FromString,
                _registered_method=True)
        self.insert_branch_details = channel.unary_unary(
                '/mydb.LibraryManagement/insert_branch_details',
                request_serializer=db__pb2.LibraryBranch.SerializeToString,
                response_deserializer=db__pb2.SuccessMessage.FromString,
                _registered_method=True)
        self.insert_transaction = channel.unary_unary(
                '/mydb.LibraryManagement/insert_transaction',
                request_serializer=db__pb2.Transaction.SerializeToString,
                response_deserializer=db__pb2.SuccessMessage.FromString,
                _registered_method=True)
        self.fetch_authors = channel.unary_unary(
                '/mydb.LibraryManagement/fetch_authors',
                request_serializer=db__pb2.Author.SerializeToString,
                response_deserializer=db__pb2.Authors.FromString,
                _registered_method=True)
        self.fetch_members = channel.unary_unary(
                '/mydb.LibraryManagement/fetch_members',
                request_serializer=db__pb2.Member.SerializeToString,
                response_deserializer=db__pb2.Members.FromString,
                _registered_method=True)
        self.fetch_books = channel.unary_unary(
                '/mydb.LibraryManagement/fetch_books',
                request_serializer=db__pb2.FetchBooksPayload.SerializeToString,
                response_deserializer=db__pb2.FetchBooksPayload.FromString,
                _registered_method=True)
        self.fetch_transactions = channel.unary_unary(
                '/mydb.LibraryManagement/fetch_transactions',
                request_serializer=db__pb2.Transaction.SerializeToString,
                response_deserializer=db__pb2.Transactions.FromString,
                _registered_method=True)
        self.update_member = channel.unary_unary(
                '/mydb.LibraryManagement/update_member',
                request_serializer=db__pb2.Member.SerializeToString,
                response_deserializer=db__pb2.SuccessMessage.FromString,
                _registered_method=True)
        self.update_book = channel.unary_unary(
                '/mydb.LibraryManagement/update_book',
                request_serializer=db__pb2.Book.SerializeToString,
                response_deserializer=db__pb2.SuccessMessage.FromString,
                _registered_method=True)
        self.update_transaction = channel.unary_unary(
                '/mydb.LibraryManagement/update_transaction',
                request_serializer=db__pb2.Transaction.SerializeToString,
                response_deserializer=db__pb2.SuccessMessage.FromString,
                _registered_method=True)
        self.delete_member = channel.unary_unary(
                '/mydb.LibraryManagement/delete_member',
                request_serializer=db__pb2.Member.SerializeToString,
                response_deserializer=db__pb2.SuccessMessage.FromString,
                _registered_method=True)
        self.delete_book = channel.unary_unary(
                '/mydb.LibraryManagement/delete_book',
                request_serializer=db__pb2.Book.SerializeToString,
                response_deserializer=db__pb2.SuccessMessage.FromString,
                _registered_method=True)
        self.delete_library_branch = channel.unary_unary(
                '/mydb.LibraryManagement/delete_library_branch',
                request_serializer=db__pb2.LibraryBranch.SerializeToString,
                response_deserializer=db__pb2.SuccessMessage.FromString,
                _registered_method=True)


class LibraryManagementServicer:
    """-------------service declaration-------------
    """

    def create_tables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def insert_book(self, request, context):
        """insert methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def insert_books_bulk(self, request, context):
        """rpc insert_books (Books) returns (SuccessMessage);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def insert_authors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def insert_members(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def insert_branch_details(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def insert_transaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def fetch_authors(self, request, context):
        """fetch methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def fetch_members(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def fetch_books(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def fetch_transactions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_member(self, request, context):
        """update methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_book(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_transaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_member(self, request, context):
        """delete methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_book(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_library_branch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LibraryManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create_tables': grpc.unary_unary_rpc_method_handler(
                    servicer.create_tables,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=db__pb2.SuccessMessage.SerializeToString,
            ),
            'insert_book': grpc.unary_unary_rpc_method_handler(
                    servicer.insert_book,
                    request_deserializer=db__pb2.Book.FromString,
                    response_serializer=db__pb2.SuccessMessage.SerializeToString,
            ),
            'insert_books_bulk': grpc.unary_unary_rpc_method_handler(
                    servicer.insert_books_bulk,
                    request_deserializer=db__pb2.CsvRequest.FromString,
                    response_serializer=db__pb2.SuccessMessage.SerializeToString,
            ),
            'insert_authors': grpc.unary_unary_rpc_method_handler(
                    servicer.insert_authors,
                    request_deserializer=db__pb2.Authors.FromString,
                    response_serializer=db__pb2.SuccessMessage.SerializeToString,
            ),
            'insert_members': grpc.unary_unary_rpc_method_handler(
                    servicer.insert_members,
                    request_deserializer=db__pb2.Members.FromString,
                    response_serializer=db__pb2.SuccessMessage.SerializeToString,
            ),
            'insert_branch_details': grpc.unary_unary_rpc_method_handler(
                    servicer.insert_branch_details,
                    request_deserializer=db__pb2.LibraryBranch.FromString,
                    response_serializer=db__pb2.SuccessMessage.SerializeToString,
            ),
            'insert_transaction': grpc.unary_unary_rpc_method_handler(
                    servicer.insert_transaction,
                    request_deserializer=db__pb2.Transaction.FromString,
                    response_serializer=db__pb2.SuccessMessage.SerializeToString,
            ),
            'fetch_authors': grpc.unary_unary_rpc_method_handler(
                    servicer.fetch_authors,
                    request_deserializer=db__pb2.Author.FromString,
                    response_serializer=db__pb2.Authors.SerializeToString,
            ),
            'fetch_members': grpc.unary_unary_rpc_method_handler(
                    servicer.fetch_members,
                    request_deserializer=db__pb2.Member.FromString,
                    response_serializer=db__pb2.Members.SerializeToString,
            ),
            'fetch_books': grpc.unary_unary_rpc_method_handler(
                    servicer.fetch_books,
                    request_deserializer=db__pb2.FetchBooksPayload.FromString,
                    response_serializer=db__pb2.FetchBooksPayload.SerializeToString,
            ),
            'fetch_transactions': grpc.unary_unary_rpc_method_handler(
                    servicer.fetch_transactions,
                    request_deserializer=db__pb2.Transaction.FromString,
                    response_serializer=db__pb2.Transactions.SerializeToString,
            ),
            'update_member': grpc.unary_unary_rpc_method_handler(
                    servicer.update_member,
                    request_deserializer=db__pb2.Member.FromString,
                    response_serializer=db__pb2.SuccessMessage.SerializeToString,
            ),
            'update_book': grpc.unary_unary_rpc_method_handler(
                    servicer.update_book,
                    request_deserializer=db__pb2.Book.FromString,
                    response_serializer=db__pb2.SuccessMessage.SerializeToString,
            ),
            'update_transaction': grpc.unary_unary_rpc_method_handler(
                    servicer.update_transaction,
                    request_deserializer=db__pb2.Transaction.FromString,
                    response_serializer=db__pb2.SuccessMessage.SerializeToString,
            ),
            'delete_member': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_member,
                    request_deserializer=db__pb2.Member.FromString,
                    response_serializer=db__pb2.SuccessMessage.SerializeToString,
            ),
            'delete_book': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_book,
                    request_deserializer=db__pb2.Book.FromString,
                    response_serializer=db__pb2.SuccessMessage.SerializeToString,
            ),
            'delete_library_branch': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_library_branch,
                    request_deserializer=db__pb2.LibraryBranch.FromString,
                    response_serializer=db__pb2.SuccessMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mydb.LibraryManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mydb.LibraryManagement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LibraryManagement:
    """-------------service declaration-------------
    """

    @staticmethod
    def create_tables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mydb.LibraryManagement/create_tables',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            db__pb2.SuccessMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def insert_book(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mydb.LibraryManagement/insert_book',
            db__pb2.Book.SerializeToString,
            db__pb2.SuccessMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def insert_books_bulk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mydb.LibraryManagement/insert_books_bulk',
            db__pb2.CsvRequest.SerializeToString,
            db__pb2.SuccessMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def insert_authors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mydb.LibraryManagement/insert_authors',
            db__pb2.Authors.SerializeToString,
            db__pb2.SuccessMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def insert_members(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mydb.LibraryManagement/insert_members',
            db__pb2.Members.SerializeToString,
            db__pb2.SuccessMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def insert_branch_details(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mydb.LibraryManagement/insert_branch_details',
            db__pb2.LibraryBranch.SerializeToString,
            db__pb2.SuccessMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def insert_transaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mydb.LibraryManagement/insert_transaction',
            db__pb2.Transaction.SerializeToString,
            db__pb2.SuccessMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def fetch_authors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mydb.LibraryManagement/fetch_authors',
            db__pb2.Author.SerializeToString,
            db__pb2.Authors.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def fetch_members(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mydb.LibraryManagement/fetch_members',
            db__pb2.Member.SerializeToString,
            db__pb2.Members.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def fetch_books(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mydb.LibraryManagement/fetch_books',
            db__pb2.FetchBooksPayload.SerializeToString,
            db__pb2.FetchBooksPayload.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def fetch_transactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mydb.LibraryManagement/fetch_transactions',
            db__pb2.Transaction.SerializeToString,
            db__pb2.Transactions.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update_member(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mydb.LibraryManagement/update_member',
            db__pb2.Member.SerializeToString,
            db__pb2.SuccessMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update_book(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mydb.LibraryManagement/update_book',
            db__pb2.Book.SerializeToString,
            db__pb2.SuccessMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update_transaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mydb.LibraryManagement/update_transaction',
            db__pb2.Transaction.SerializeToString,
            db__pb2.SuccessMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_member(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mydb.LibraryManagement/delete_member',
            db__pb2.Member.SerializeToString,
            db__pb2.SuccessMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_book(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mydb.LibraryManagement/delete_book',
            db__pb2.Book.SerializeToString,
            db__pb2.SuccessMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_library_branch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mydb.LibraryManagement/delete_library_branch',
            db__pb2.LibraryBranch.SerializeToString,
            db__pb2.SuccessMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
