// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Header from "./components/common/header";
// import Footer from "./components/common/footer";
// import Sidebar from "./components/common/sidebar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">
//         <Header />
//         {/* <Sidebar /> */}

//         {children}

//         {/* <Footer /> */}
//       </body>
//     </html>
//   );
// }


import "./globals.css";
import Header from "./components/common/header";
import Footer from "./components/common/footer";
import Sidebar from "./components/common/sidebar";

export const metadata = {
    title: "Library Management",
    description: "Library Management System",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="h-full antialiased">
            <body className="min-h-full flex flex-col">
                <Header />

                {/* <Sidebar /> */}

                <main className="flex-1">
                    {children}
                </main>

                {/* <Footer /> */}
            </body>
        </html>
    );
}
